# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-09 09:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=200)),
                ('level_1_time', models.CharField(max_length=200)),
                ('level_1_unlock', models.BooleanField(default=False)),
                ('level_2_time', models.CharField(max_length=200)),
                ('level_2_unlock', models.BooleanField(default=False)),
                ('level_3_time', models.CharField(max_length=200)),
                ('level_3_unlock', models.BooleanField(default=False)),
                ('level_4_time', models.CharField(max_length=200)),
                ('level_4_unlock', models.BooleanField(default=False)),
                ('level_5_time', models.CharField(max_length=200)),
                ('level_5_unlock', models.BooleanField(default=False)),
                ('total_time', models.CharField(max_length=200)),
            ],
        ),
    ]
