# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-09 19:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colorex', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='total_time_numeric',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
