# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-05-12 10:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colorex', '0002_user_total_time_numeric'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='level_10_time',
            field=models.CharField(default='0', max_length=200),
        ),
        migrations.AddField(
            model_name='user',
            name='level_10_unlock',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='level_6_time',
            field=models.CharField(default='0', max_length=200),
        ),
        migrations.AddField(
            model_name='user',
            name='level_6_unlock',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='level_7_time',
            field=models.CharField(default='0', max_length=200),
        ),
        migrations.AddField(
            model_name='user',
            name='level_7_unlock',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='level_8_time',
            field=models.CharField(default='0', max_length=200),
        ),
        migrations.AddField(
            model_name='user',
            name='level_8_unlock',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='level_9_time',
            field=models.CharField(default='0', max_length=200),
        ),
        migrations.AddField(
            model_name='user',
            name='level_9_unlock',
            field=models.BooleanField(default=False),
        ),
    ]
