# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-01-20 12:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colorex', '0004_auto_20190119_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_a_user_name',
            field=models.BooleanField(default=False),
        ),
    ]
